"""
wallet_fix.py
=============
Run this ONCE to fix the wallet and verify everything works.

What it does:
1. Installs the real Midnight wallet SDK (Node.js packages)
2. Derives your REAL wallet address using the official SDK
3. Creates accounts.json for midnight-local-dev funding
4. Checks your balance
5. Tells you exactly what to do next

Run:
    python wallet_fix.py
"""

import subprocess
import sys
import json
import os
from pathlib import Path

MNEMONIC = (
    "license crack common laugh ten three age fish security original "
    "hour broken milk library limb tornado prison source lumber crystal "
    "found risk anger around"
)

MIDNIGHT_LOCAL_DEV = Path("../midnight-local-dev")


def step(msg):
    print(f"\n{'='*55}")
    print(f"  {msg}")
    print('='*55)


def run(cmd, cwd=None, env=None):
    result = subprocess.run(
        cmd, shell=True, capture_output=True, text=True,
        cwd=cwd, env=env or os.environ
    )
    return result


def install_wallet_sdk():
    step("Installing real Midnight wallet SDK...")
    pkg = Path("package_wallet.json")
    if not pkg.exists():
        print("  ERROR: package_wallet.json not found in repo root")
        sys.exit(1)

    # Copy to package.json for npm install
    import shutil
    shutil.copy(pkg, "package.json")

    result = run("npm install")
    if result.returncode != 0:
        print(f"  npm install failed:\n{result.stderr}")
        print("  Make sure Node.js 22+ is installed: node --version")
        sys.exit(1)
    print("  ✓ Wallet SDK installed OK")
    # Restore original package.json if it existed
    if Path("package.json").read_text() == pkg.read_text():
        Path("package.json").unlink(missing_ok=True)


def get_real_address():
    step("Deriving REAL wallet address using official Midnight SDK...")
    
    result = run(
        "node get_wallet_address.mjs",
        env={**os.environ, "MNEMONIC": MNEMONIC, "NETWORK_ID": "undeployed"}
    )
    
    if result.returncode != 0 or not result.stdout.strip():
        print(f"  Failed: {result.stderr}")
        print("  Is the local network running? cd midnight-local-dev && npm start")
        return None
    
    try:
        data = json.loads(result.stdout.strip())
        print(f"  Real address:  {data['address']}")
        print(f"  DUST balance:  {data['dust']}")
        print(f"  NIGHT balance: {data['night']}")
        return data
    except json.JSONDecodeError:
        print(f"  Could not parse output: {result.stdout}")
        return None


def create_accounts_json(address):
    step("Creating accounts.json for midnight-local-dev...")

    accounts = {
        "accounts": [
            {
                "name": "SamratSDK",
                "mnemonic": MNEMONIC
            }
        ]
    }

    # Write to midnight-local-dev if it exists
    if MIDNIGHT_LOCAL_DEV.exists():
        target = MIDNIGHT_LOCAL_DEV / "accounts.json"
        with open(target, "w") as f:
            json.dump(accounts, f, indent=2)
        print(f"  Created: {target}")
    else:
        # Write locally
        with open("accounts.json", "w") as f:
            json.dump(accounts, f, indent=2)
        print("  Created: ./accounts.json")
        print(f"  Copy this to your midnight-local-dev folder!")

    return accounts


def main():
    print("\n" + "🌙 " * 10)
    print("  Midnight Wallet Fix — Real Address Derivation")
    print("🌙 " * 10)

    # 1. Install SDK
    install_wallet_sdk()

    # 2. Get real address
    wallet_data = get_real_address()

    if not wallet_data:
        step("Could not connect to network — offline derivation")
        print("  Start the network first:")
        print("  cd midnight-local-dev && npm start")
        print("\n  Then run: python wallet_fix.py again")
        return

    # 3. Save real address
    with open(".wallet_real.json", "w") as f:
        json.dump({
            "address": wallet_data["address"],
            "network": "undeployed",
            "note": "Generated by real Midnight SDK — DO NOT COMMIT"
        }, f, indent=2)
    print(f"\n  Saved to: .wallet_real.json")

    # 4. Create accounts.json
    create_accounts_json(wallet_data["address"])

    # 5. Check if already funded
    dust = int(wallet_data.get("dust", 0))
    night = int(wallet_data.get("night", 0))

    step("Summary")
    if dust > 0 and night > 0:
        print(f"  ✓ Wallet is FUNDED and READY!")
        print(f"  Address: {wallet_data['address']}")
        print(f"  DUST:    {dust:,}")
        print(f"  NIGHT:   {night:,}")
        print(f"\n  Run the demo: python examples/private_ml_demo.py")
    else:
        print(f"  Address: {wallet_data['address']}")
        print(f"  DUST:    {dust} ← needs funding")
        print(f"  NIGHT:   {night} ← needs funding")
        print("""
  Your wallet needs tokens. Do this:

  1. Open terminal 1 (keep running):
      cd midnight-local-dev
      npm start

  2. When menu appears:
      > 1
      Path: ./accounts.json

  3. Wait for "Funding complete"

  4. Run this script again to verify:
      python wallet_fix.py
""")


if __name__ == "__main__":
    main()
